@base_url = 
@rootDomain = 
@authToken = 
@token = 
@username = 
@domain = 
@service = 
@ghostID = 
@dataSchema = 
@timeout = 
@links = 
@refDomain = 
@refService = 
@refGhostID = 

### Service features

###
curl -X POST {{base_url}}/api/services \ 
-H "Content-Type: application/json" \ 
-d '{
  "domainName":"{{domain}}",
  "rootDomain":"{{rootDomain}}",
  "token":"{{token}}"
}'

###
curl -X POST {{base_url}}/api/services/create \ 
-H "Content-Type: application/json" \ 
-d '{
  "domain":"{{domain}}",
  "rootDomain":"{{rootDomain}}",
  "service":"{{service}}",
  "token":"{{token}}",
  "username":"{{username}}",
  "authToken":"{{authToken}}",
  "dataSchema":"{{dataSchema}}",
  "timeout":"{{timeout}}"
}'

###
curl -X POST {{base_url}}/api/services/update \ 
-H "Content-Type: application/json" \ 
-d '{
  "domain":"{{domain}}",
  "rootDomain":"{{rootDomain}}",
  "service":"{{service}}",
  "token":"{{token}}",
  "dataSchema":"{{dataSchema}}",
  "timeout":"{{timeout}}"
}'

###
curl -X POST {{base_url}}/api/services/links/update \ 
-H "Content-Type: application/json" \ 
-d '{
  "domain":"{{domain}}",
  "rootDomain":"{{rootDomain}}",
  "service":"{{service}}",
  "token":"{{token}}",
  "links":{{links}}
}'

###
curl -X POST {{base_url}}/api/services/links \ 
-H "Content-Type: application/json" \ 
-d '{
  "domain":"{{domain}}",
  "rootDomain":"{{rootDomain}}",
  "service":"{{service}}",
  "token":"{{token}}"
}'

### Ghost features

###
curl -X POST {{base_url}}/api/ghosts \ 
-H "Content-Type: application/json" \ 
-d '{
  "domain":"{{domain}}",
  "rootDomain":"{{rootDomain}}",
  "token":"{{token}}"
}'

###
curl -X POST {{base_url}}/api/ghosts/pending \ 
-H "Content-Type: application/json" \ 
-d '{
  "domain":"{{domain}}",
  "rootDomain":"{{rootDomain}}",
  "token":"{{token}}",
  "username":"{{username}}"
}'

###
curl -X POST {{base_url}}/api/ghosts/pending/accept \ 
-H "Content-Type: application/json" \ 
-d '{
  "domain":"{{domain}}",
  "rootDomain":"{{rootDomain}}",
  "service":"{{service}}",
  "token":"{{token}}",
  "username":"{{username}}",
  "ghostID":"{{ghostID}}"
}'

###
curl -X POST {{base_url}}/api/ghosts/morphed/add \ 
-H "Content-Type: application/json" \ 
-d '{
  "domain":"{{domain}}",
  "rootDomain":"{{rootDomain}}",
  "service":"{{service}}",
  "token":"{{token}}",
  "ghostID":"{{ghostID}}",
  "refDomain":"{{refDomain}}",
  "refService":"{{refService}}",
  "refGhostID":"{{refGhostID}}"
}'

###
curl -X POST {{base_url}}/api/ghosts/morphed/remove \ 
-H "Content-Type: application/json" \ 
-d '{
  "domain":"{{domain}}",
  "rootDomain":"{{rootDomain}}",
  "service":"{{service}}",
  "token":"{{token}}",
  "ghostID":"{{ghostID}}",
  "refDomain":"{{refDomain}}",
  "refService":"{{refService}}",
  "refGhostID":"{{refGhostID}}"
}'